# Generated by Django 4.2.27 on 2025-12-31 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('direct', 'پرداخت مستقیم'), ('installment', 'اعتباری/اقساطی')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('canceled', 'لغو شده')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product'),
        ),
    ]
