# Generated by Django 4.2.27 on 2025-12-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی\u200cها'},
        ),
        migrations.AlterField(
            model_name='product',
            name='base_sale_price',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='عکس اصلی (URL)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت خرید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=85000, max_digits=12, verbose_name='هزینه ارسال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_url',
            field=models.URLField(max_length=1000, unique=True, verbose_name='لینک منبع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=10, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='is_video',
            field=models.BooleanField(default=False, verbose_name='ویدیو است؟'),
        ),
    ]
