# Generated by Django 4.2.27 on 2025-12-30 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('birthDate', models.CharField(max_length=20, verbose_name='تاریخ تولد')),
                ('amount', models.BigIntegerField(default=0, verbose_name='مبلغ وام')),
                ('installments', models.IntegerField(default=12, verbose_name='تعداد اقساط')),
                ('tracking_code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='کد رهگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار اعتبار سنجی'), ('approved', 'تأیید اولیه (نیاز به مدارک)'), ('verifying', 'در انتظار تأیید مدارک'), ('completed', 'تأیید نهایی و واریز شده'), ('rejected', 'رد شده')], default='pending', max_length=30, verbose_name='وضعیت')),
                ('birth_certificate', models.ImageField(blank=True, null=True, upload_to='docs/birth/', verbose_name='تصویر شناسنامه')),
                ('id_card_front', models.ImageField(blank=True, null=True, upload_to='docs/id/', verbose_name='روی کارت ملی')),
                ('id_card_back', models.ImageField(blank=True, null=True, upload_to='docs/id/', verbose_name='پشت کارت ملی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.BigIntegerField(default=0, verbose_name='موجودی کیف پول اعتباری')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name='شماره قسط')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ قسط اصل')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت واقعی')),
                ('credit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments_list', to='credit.creditrequest')),
            ],
        ),
    ]
