# Generated by Django 4.2.27 on 2026-01-04 20:04

import credit.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_code', models.CharField(default=credit.models._generate_tracking_code, max_length=24, unique=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('installments', models.PositiveIntegerField(default=12)),
                ('status', models.CharField(choices=[('pending', 'در انتظار اعتبار سنجی'), ('approved', 'تأیید اولیه (نیاز به مدارک)'), ('verifying', 'در انتظار تأیید مدارک'), ('completed', 'تأیید نهایی و واریز شده'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('credited_to_wallet', models.BooleanField(default=False)),
                ('national_card_front', models.FileField(blank=True, null=True, upload_to='credit_docs/')),
                ('national_card_back', models.FileField(blank=True, null=True, upload_to='credit_docs/')),
                ('salary_slip', models.FileField(blank=True, null=True, upload_to='credit_docs/')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='credit_docs/')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='credit_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=120)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('nationalCode', models.CharField(max_length=20)),
                ('postalCode', models.CharField(max_length=20)),
                ('preciseAddress', models.TextField()),
                ('city', models.CharField(default='تهران', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.BigIntegerField(default=0)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('credit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments_list', to='credit.creditrequest')),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('credit_request', 'installment_number')},
            },
        ),
    ]
