# Generated by Django 4.2.27 on 2026-01-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کامل'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='payment_track_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری پرداخت'),
        ),
    ]
