# Generated by Django 4.2.27 on 2025-12-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditrequest',
            name='birth_certificate',
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='id_card_back',
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='id_card_front',
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='wallet_charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='birthDate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='fullName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='installments',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='national_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار اعتبار سنجی'), ('approved', 'تأیید اولیه'), ('verifying', 'در انتظار مدارک'), ('completed', 'تأیید نهایی'), ('rejected', 'رد شده')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='installment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='installment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='inventory',
            field=models.BigIntegerField(default=0),
        ),
    ]
