# Generated by Django 4.2.27 on 2025-12-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_remove_creditrequest_birth_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditrequest',
            name='wallet_charged',
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='birth_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='docs/birth/', verbose_name='تصویر شناسنامه'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='docs/id/', verbose_name='پشت کارت ملی'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='docs/id/', verbose_name='روی کارت ملی'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='amount',
            field=models.BigIntegerField(default=0, verbose_name='مبلغ وام'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='birthDate',
            field=models.CharField(max_length=20, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='fullName',
            field=models.CharField(max_length=255, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='installments',
            field=models.IntegerField(default=12, verbose_name='تعداد اقساط'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='national_id',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار اعتبار سنجی'), ('approved', 'تأیید اولیه (نیاز به مدارک)'), ('verifying', 'در انتظار تأیید مدارک'), ('completed', 'تأیید نهایی و واریز شده'), ('rejected', 'رد شده')], default='pending', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.BigIntegerField(verbose_name='مبلغ قسط اصل'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateField(verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_number',
            field=models.IntegerField(verbose_name='شماره قسط'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت واقعی'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='inventory',
            field=models.BigIntegerField(default=0, verbose_name='موجودی کیف پول اعتباری'),
        ),
    ]
