# Generated by Django 4.2.27 on 2025-12-31 16:11

import credit.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit', '0003_remove_creditrequest_wallet_charged_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['installment_number']},
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='birthDate',
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='id_card_back',
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='id_card_front',
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='inventory',
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='credit_docs/'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='credited_to_wallet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='national_card_back',
            field=models.FileField(blank=True, null=True, upload_to='credit_docs/'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='national_card_front',
            field=models.FileField(blank=True, null=True, upload_to='credit_docs/'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='salary_slip',
            field=models.FileField(blank=True, null=True, upload_to='credit_docs/'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='credit_docs/'),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='installments',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار اعتبار سنجی'), ('approved', 'تأیید اولیه (نیاز به مدارک)'), ('verifying', 'در انتظار تأیید مدارک'), ('completed', 'تأیید نهایی و واریز شده'), ('rejected', 'رد شده')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditrequest',
            name='tracking_code',
            field=models.CharField(default=credit.models._generate_tracking_code, max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='installment',
            name='installment_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('credit_request', 'installment_number')},
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=120)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('nationalCode', models.CharField(max_length=20)),
                ('postalCode', models.CharField(max_length=20)),
                ('preciseAddress', models.TextField()),
                ('city', models.CharField(default='تهران', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='installment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='installment',
            name='payment_date',
        ),
    ]
